name: fraud_analytics
version: 1.0.0
config-version: 2

profile: fraud_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  fraud_analytics:
    staging:
      +materialized: view
